services:
  auth_api:
    build:
      context: .
      dockerfile: local.Dockerfile
    container_name: auth_api
    ports:
      - "8000:8000"
    env_file:
      .env
    volumes:
      - ./alembic:/app/alembic
    networks:
      - auth
    depends_on:
      auth_db:
        condition: service_healthy
    restart: unless-stopped

  auth_db:
    image: postgres:17.4
    container_name: auth_db
    env_file:
      - .env
    ports:
      - "5471:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - auth
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth_redis:
    image: redis:7
    container_name: auth_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - auth
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeper
    env_file:
      - .env
    networks:
      - auth

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    env_file:
      - .env
    networks:
      - auth
    healthcheck:
      test: ["CMD", "bash", "-c", "nc -z localhost 9092"]
      interval: 10s
      timeout: 5s
      retries: 10

  go_consumer:
    build:
      context: ./clickHouseConsumer
    container_name: go_consumer
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - auth

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    env_file:
      - .env
    volumes:
      - ./clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - auth
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  pg_data:
  clickhouse_data:

networks:
  auth:
    driver: bridge